import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const coreRoot = join(__dirname, "..");
export const defaultPromptsRoot = join(coreRoot, "prompts");
export const defaultOutFile = join(coreRoot, "src/prompts/generated-prompts.ts");

/**
 * @param {string} dir
 * @param {string} promptsRoot
 * @returns {{ key: string, content: string }[]}
 */
export function collectPromptEntries(dir, promptsRoot = dir) {
  /** @type {{ key: string, content: string }[]} */
  const entries = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      entries.push(...collectPromptEntries(full, promptsRoot));
      continue;
    }
    if (!name.endsWith(".md")) {
      continue;
    }
    const key = relative(promptsRoot, full).split("\\").join("/");
    entries.push({ key, content: readFileSync(full, "utf8") });
  }
  return entries;
}

/**
 * @param {{ key: string, content: string }[]} entries
 * @returns {string}
 */
export function renderGeneratedPromptsModule(entries) {
  const sorted = [...entries].sort((a, b) => a.key.localeCompare(b.key));
  const keys = sorted.map((entry) => entry.key);
  const promptType =
    keys.length === 0
      ? "string"
      : keys.map((key) => JSON.stringify(key)).join(" | ");

  const lines = [
    "/** Generated by engine/core/scripts/generate-prompts.mjs — do not edit. */",
    "",
    `export type PromptKey = ${promptType};`,
    "",
    "export const PROMPTS: Record<PromptKey, string> = {",
  ];

  for (const { key, content } of sorted) {
    lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(content)},`);
  }

  lines.push("};", "");
  return lines.join("\n");
}

/**
 * @param {{ promptsRoot?: string, outFile?: string }} [options]
 */
export function generatePrompts(options = {}) {
  const promptsRoot = options.promptsRoot ?? defaultPromptsRoot;
  const outFile = options.outFile ?? defaultOutFile;
  const entries = collectPromptEntries(promptsRoot);
  const source = renderGeneratedPromptsModule(entries);
  writeFileSync(outFile, source, "utf8");
  return { outFile, count: entries.length };
}

const isMain =
  Boolean(process.argv[1]) &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const { outFile, count } = generatePrompts();
  console.info(`[core] wrote ${count} prompts → ${outFile}`);
}
