services:
  hive-worker:
    build:
      context: ../..
      dockerfile: worker/Dockerfile
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - worker.config.env
      - /etc/hive-worker/worker.env
