/** Human review queues — consumed by rulebook-report. Not loaded at runtime. */

/** Rule refs cited by terms but without an HTML `RULES` summary (empty `Rule.plain`). */
export const missingRuleSummaries: string[] = [
  "idea:300.1",
  "idea:300.5",
  "idea:300.6",
  "idea:300.8(c)(10)",
  "idea:300.9",
  "idea:300.17",
  "idea:300.22",
  "idea:300.28",
  "idea:300.34",
  "idea:300.34(c)(6)",
  "idea:300.34(c)(15)",
  "idea:300.39(b)(3)",
  "idea:300.41",
  "idea:300.42",
  "idea:300.43",
  "idea:300.114",
  "idea:300.115",
  "idea:300.160",
  "idea:300.160(c)",
  "idea:300.306",
  "idea:300.320",
  "idea:300.320(a)(1)(i)",
  "idea:300.320(a)(2)(ii)",
  "idea:300.320(a)(3)(i)",
  "idea:300.320(a)(3)(ii)",
  "idea:300.320(b)(1)",
  "idea:300.320(c)",
  "idea:300.321",
  "idea:300.324(a)(1)(ii)",
  "idea:300.324(a)(2)",
  "idea:300.324(a)(2)(ii)",
  "idea:300.520",
  "idea:300.530(d)",
  "idea:300.530(f)",
];

export const unmappedSlots: string[] = [
  "goal.frequency",
  "goal.duration",
  "goal.mastery",
  "services.minutes",
  "services.setting",
  "accommodation.extendedTime",
  "accommodation.textToSpeech",
  "placement.minutesOutsideGenEd",
];

/** Demo questions from hive-your-plan.html — not yet templated over pack slots. */
export const unmappedQuestions: string[] = [
  "present: How does reading comprehension affect Caleb in his other classes, like science and social studies?",
  "present: Where in the IEP are his present levels written, and do they mention both reading fluency and comprehension?",
  "goals: What kind of passages and questions make up the 80% comprehension probes?",
  "goals: The 2023 fluency goal was last marked not met. How was that addressed before it was removed — was the 104 score used?",
  "goals: Will reading fluency still be checked anywhere this year?",
  "progress: Will each quarterly report show the probe scores, or just a rating?",
  "progress: Can you see probe results between reports?",
  "services: The main need changed from fluency to comprehension, but the service amount stayed the same. Will the instruction itself change?",
  "services: Who provides the reading instruction, and what program or method is used?",
  "supports: Do these supports apply on state tests as well as classroom tests?",
  "supports: Who makes sure text-to-speech is available in each class?",
  "lre: What part of the school day does Caleb leave the regular class for reading, and what does he miss?",
  "factors: Where are your concerns written in the IEP? If they aren’t, you can ask for them to be added.",
  "factors: Was assistive technology considered for reading?",
  "esy: Did the team discuss whether Caleb needs reading support over the summer?",
];
